# Generated by Django 5.1.1 on 2024-09-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.TextField(default=None, max_length=1000)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hackathon_images')),
            ],
        ),
    ]
