# Generated by Django 4.2.16 on 2024-09-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_submission_type',
            field=models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('link', 'Link')], default='Link', max_length=10),
        ),
    ]
